"""add patient_id to users

Revision ID: 6ac6d5b3b41f
Revises: 8789ee81856c
Create Date: 2026-06-27 18:47:15.083330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac6d5b3b41f'
down_revision: Union[str, None] = '8789ee81856c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('patient_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'patient_id')
    # ### end Alembic commands ###
